### PR TITLE
PMM-4672 Round percent in labels

### PR DESCRIPTION
**Pull request by darly-s**
https://jira.percona.com/browse/PMM-4672

### CODE REVIEW

**Comment by AlekSi** [comment]
Should anything be done there?

**Comment by BupycHuk** [comment]
I'll check

**Comment by AlekSi** [comment]
@BupycHuk anything we should do there? Close and remove?

**Comment by BupycHuk** [comment]
Not yet, haven't checked yet

**Comment by AlekSi** [comment]
Is it a draft without FB?

**Comment by BupycHuk** [comment]
@lunaticusgreen could you fix merge conflicts, please?

**Comment by lunaticusgreen** [comment]
Yes, I'll do it

**Pull request merged**
