### PR TITLE
PMM-4477 Remote node monitoring.

### PR DESCRIPTION
**Pull request by rnovikovP**

### CODE REVIEW

**Comment by AlekSi** [comment]
@askomorokhov PTAL

**Comment by AlekSi** [comment]
@BupycHuk please resolve merge conflicts. And I think we can no longer wait for @darly-s.

**Comment by BupycHuk** [comment]
@AlekSi I made new changes since @askomorokhov approved this PR. I would like to hime review new change if you don't mind.

**Comment by AlekSi** [comment]
I don't mind because I have no idea :) Still, there is a merge conflict.

**Pull request merged**
